# Srevin Saju (c) 2020
# MIT License
# Source: https://github.com/srevinsaju/guiscrcpy


name: Continuous

on: 
  - push

jobs:
  Wheel:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        version: ['3.8']
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.version }}

    - name: Build wheel
      run: |
        python -m pip install wheel
        python setup.py bdist_wheel
        export VERSION=$(ls dist)

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: aslo4-continuous-none-any-py3.whl
        path: dist/${{ env.VERSION }}

  Release:
    needs: [Wheel]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [3.8]

    steps:

    - uses: actions/download-artifact@v4.1.7
      with:
        name: aslo4-continuous-none-any-py3.whl

    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      if: github.ref == 'refs/heads/master' && startsWith(github.ref, 'refs/tags/') != true
      with:
        automatic_release_tag: continuous
        title: continuous
        files: |
          aslo4-continuous-none-any-py3.whl
          
        repo_token: ${{ secrets.GITHUB_TOKEN }}
