# Srevin Saju (c) 2020
# MIT License
# Source: https://github.com/srevinsaju/guiscrcpy


name: Continuous

on: 
  - push

jobs:
  Wheel:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        version: ['3.8']
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.version }}

    - name: Build wheel
      run: |
        python -m pip install wheel
        python setup.py bdist_wheel
        export VERSION=$(ls dist)

    - name: Build AppImage
      run: |
        wget https://github.com/srevinsaju/pyappimage/releases/download/continuous/pyappimage-3.8-x86_64.AppImage
        chmod +x pyappimage-3.8-x86_64.AppImage
        ./pyappimage-*.AppImage build
        wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x appimagetool-x86_64.AppImage
        ./appimagetool*.AppImage -n -u 'gh-releases-zsync|sugarlabs|aslo-v4|latest|aslo4*.AppImage.zsync' ./*.AppDir
        mkdir appimage_dist/
        mv asl*.AppImage* appimage_dist/. 

    - name: Upload artifact AppImage
      uses: actions/upload-artifact@v1.0.0
      with:
        name: aslo4-continuous-appimage.AppImage.zip
        path: appimage_dist/

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: aslo4-continuous-none-any-py3.whl
        path: dist/${{ env.VERSION }}

  Release:
    needs: [Wheel]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [3.8]

    steps:

    - uses: actions/download-artifact@v1
      with:
        name: aslo4-continuous-none-any-py3.whl

    - uses: actions/download-artifact@v1
      with: 
        name: aslo4-continuous-appimage.AppImage.zip
        
    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      if: github.ref == 'refs/heads/master' && startsWith(github.ref, 'refs/tags/') != true
      with:
        automatic_release_tag: continuous
        title: continuous
        files: |
          aslo4-continuous-none-any-py3.whl
          aslo4-continuous-appimage.AppImage.zip
          
        repo_token: ${{ secrets.GITHUB_TOKEN }}
